### ISSUE TITLE
Any image? I won't install it if it not cool 

### ISSUE THREAD

**Issue by Thadzy** [Logical05/zsh-template#1]
### **Any image? I won't install it if it not cool**

**Comment by Logical05** [comment]
![Screenshot from 2024-12-30 12-43-30](https://github.com/user-attachments/assets/d5e176cf-7770-475f-816a-a456d4ead41c)
You can customize it to your own style. For more details, see [Configuration](https://github.com/Logical05/zsh-template?tab=readme-ov-file#configuration).
